// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3TbbnBQyC9_cJqnc7wSQOzn__afDEPZ8',
    appId: '1:556102451347:web:4c0440c167656a77a54d66',
    messagingSenderId: '556102451347',
    projectId: 'authfluttermobilodev',
    authDomain: 'authfluttermobilodev.firebaseapp.com',
    storageBucket: 'authfluttermobilodev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtEBRJwbUNoACB9a8y64lzUzxNxM88ngs',
    appId: '1:556102451347:android:5f627cbd8b36b238a54d66',
    messagingSenderId: '556102451347',
    projectId: 'authfluttermobilodev',
    storageBucket: 'authfluttermobilodev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsM7thN3jx9QcFemWu_cHCxQnxIFDtjkg',
    appId: '1:556102451347:ios:4958eae14e0baa0ba54d66',
    messagingSenderId: '556102451347',
    projectId: 'authfluttermobilodev',
    storageBucket: 'authfluttermobilodev.appspot.com',
    iosBundleId: 'com.example.flutterKisilerBlocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsM7thN3jx9QcFemWu_cHCxQnxIFDtjkg',
    appId: '1:556102451347:ios:f7564869b6edbaf4a54d66',
    messagingSenderId: '556102451347',
    projectId: 'authfluttermobilodev',
    storageBucket: 'authfluttermobilodev.appspot.com',
    iosBundleId: 'com.example.flutterKisilerBlocFirebase.RunnerTests',
  );
}
